---
minimum_pre_commit_version: 2.4.0
repos:
  # renovate:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]

  # renovate: depName=actionlint
  - repo: https://github.com/kjanat/actionlint
    rev: 08bb2c4f0d039744455b87aef1c647fb8b66d37b  # v1.17.0
    hooks:
      - id: actionlint-shellcheck
        alias: actionlint

  # renovate: depName=renovate
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 32202df16e5e41bb0582ecfa41f7d1dcaf7d4d08  # 44.149.2
    hooks:
      - id: renovate-config-validator
        alias: renovate-global
        name: Validate Global Renovate Config
        files: ^\.github/renovate-global.json5$
        args:
          - --strict

      - id: renovate-config-validator
        alias: renovate
        name: Validate Repository Renovate Config
        args:
          - --no-global  # Passing filenames results in the validator treating it as global by default
          - --strict
