---
minimum_pre_commit_version: 2.4.0
repos:
  # renovate:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]

  # renovate: depName=actionlint
  - repo: https://github.com/kjanat/actionlint
    rev: 2da2ceb4af2c7ecc48f5b9311d85080c3971b5f0  # v1.17.0
    hooks:
      - id: actionlint-shellcheck
        alias: actionlint

  # renovate: depName=renovate
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 95bb5478d9f732658452e5bc0dfbeb986832faa9  # 44.138.0
    hooks:
      - id: renovate-config-validator
        alias: renovate-global
        name: Validate Global Renovate Config
        files: ^\.github/renovate-global.json5$
        args:
          - --strict

      - id: renovate-config-validator
        alias: renovate
        name: Validate Repository Renovate Config
        args:
          - --no-global  # Passing filenames results in the validator treating it as global by default
          - --strict
